In [ ]:
import ast
import pandas as pd

#from transformers import pipeline # uncomment to regenerate annotations
#import treetaggerwrapper # uncomment to regenerate annotations
#import stanza # uncomment to regenerate annotations

from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score

# Load Test Dataset

In [2]:
data_path = "../data/fine-tuning/"
test_df = pd.read_csv(data_path + "mwb-texts_NER_test.tsv", sep="\t", converters={0: ast.literal_eval, 1: ast.literal_eval})
test_df

,tokens,labels
0,"[sîn, ungevüegez, rîs, in, der, hende, als, ei...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
1,"[hiez, daz, aller, valsch, an, im, verswant,, ...","[O, O, O, O, O, O, O, O, O, O, B, O, O, O, O, ..."
2,"[het, aldâ, genomn, der, stolze, küene, Wâleis...","[O, O, O, O, O, O, B, B, O, B, O, B, B, B, O, ..."
3,"[erslagn., nu, vergebt, im, sîne, schulde, dur...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
4,"[umbe, begunder, gâhen,, des, küneges, vanen, ...","[O, O, O, O, O, O, O, O, O, O, B, O, O, O, O, ..."
...,...,...
595,"[guoten, ritter, zimet,, swenn, er, den, schil...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
596,"[der, brust, bewart,, so, ist, werder, prîs, d...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
597,"[ein, herre, genant, alsus,, der, künec, Iels,...","[O, O, O, O, O, O, B, O, B, O, B, O, O, B, B, ..."
598,"[vor, im, her, gesant,, sît, ichz, lebende, im...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
599,"[lêret, ir, mûze, alsus, volrecken,, nâch, den...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."

In [3]:
def evaluate(y_true, y_predicted):
    return {
        "precision": float(round( precision_score(y_true, y_predicted, pos_label="B", zero_division=0), 4)),
        "recall": float(round( recall_score(y_true, y_predicted, pos_label="B", zero_division=0), 4)),
        "f1_macro": float(round( f1_score(y_true, y_predicted, average="macro", zero_division=0), 4)),
        "accuracy": float(round( accuracy_score(y_true, y_predicted), 4))
    }

y_true = list(test_df["labels"].explode())

# Evaluate Random

In [4]:
import random

labels = list(sorted(set(y_true)))
random.seed(0)
y_random = random.choices(labels, k=len(y_true))

evaluate(y_true, y_random)

{'precision': 0.0671, 'recall': 0.4746, 'f1_macro': 0.384, 'accuracy': 0.4993}

# Evaluate Majority Baseline

In [5]:
majority_test_df = test_df[["tokens"]].copy()
majority_test_df["labels"] = majority_test_df["tokens"].apply(lambda x: ["O" for token in x])

majority_test_df

,tokens,labels
0,"[sîn, ungevüegez, rîs, in, der, hende, als, ei...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
1,"[hiez, daz, aller, valsch, an, im, verswant,, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
2,"[het, aldâ, genomn, der, stolze, küene, Wâleis...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
3,"[erslagn., nu, vergebt, im, sîne, schulde, dur...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
4,"[umbe, begunder, gâhen,, des, küneges, vanen, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
...,...,...
595,"[guoten, ritter, zimet,, swenn, er, den, schil...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
596,"[der, brust, bewart,, so, ist, werder, prîs, d...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
597,"[ein, herre, genant, alsus,, der, künec, Iels,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
598,"[vor, im, her, gesant,, sît, ichz, lebende, im...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
599,"[lêret, ir, mûze, alsus, volrecken,, nâch, den...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."

In [6]:
y_majority = list(majority_test_df["labels"].explode())

evaluate(y_true, y_majority)

{'precision': 0.0, 'recall': 0.0, 'f1_macro': 0.4818, 'accuracy': 0.9298}

# Evaluate Fine-tuned gbert

In [7]:
def get_aligned_labels(tokens, y_predicted):
    # get start/end indices
    start_end_data = [(y["start"], y["end"]) for y in y_predicted]
    
    # build labels
    labels = []
    i = 0
    start = 0
    end = 0
    for word in tokens:
        end = start + len(word)
        label = "O"
        for j, entity in enumerate(start_end_data[i:]):
            if start <= entity[0] and end >= entity[1]:
                i += j
                label = "B"
                break
        labels.append(label)
        start = end + 1
    return labels

In [ ]:
#gbert_path = "../models/gbert-base-mwb-NER" # uncomment to regenerate annotations
#gbert = pipeline("token-classification", model=gbert_path)
#finetuned_gbert_test_df = test_df[["tokens"]].copy()
#finetuned_gbert_test_df["labels"] = finetuned_gbert_test_df["tokens"].apply(lambda x: get_aligned_labels(x, gbert(" ".join(x), aggregation_strategy="first")))
#finetuned_gbert_test_df.to_csv("../data/predictions/mwb-texts_NER_test_gbert.tsv", sep="\t", index=False)

finetuned_gbert_test_df = pd.read_csv("../data/predictions/mwb-texts_NER_test_gbert.tsv", sep="\t", converters={0: ast.literal_eval, 1: ast.literal_eval})
finetuned_gbert_test_df

,tokens,labels
0,"[sîn, ungevüegez, rîs, in, der, hende, als, ei...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
1,"[hiez, daz, aller, valsch, an, im, verswant,, ...","[O, O, O, O, O, O, O, O, O, O, B, O, O, O, O, ..."
2,"[het, aldâ, genomn, der, stolze, küene, Wâleis...","[O, O, O, O, O, O, B, B, O, B, O, B, B, B, O, ..."
3,"[erslagn., nu, vergebt, im, sîne, schulde, dur...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
4,"[umbe, begunder, gâhen,, des, küneges, vanen, ...","[O, O, O, O, O, O, O, O, O, O, B, O, O, O, O, ..."
...,...,...
595,"[guoten, ritter, zimet,, swenn, er, den, schil...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
596,"[der, brust, bewart,, so, ist, werder, prîs, d...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
597,"[ein, herre, genant, alsus,, der, künec, Iels,...","[O, O, O, B, O, O, B, O, B, O, B, O, O, B, B, ..."
598,"[vor, im, her, gesant,, sît, ichz, lebende, im...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
599,"[lêret, ir, mûze, alsus, volrecken,, nâch, den...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."

In [9]:
y_gbert = list(finetuned_gbert_test_df["labels"].explode())

evaluate(y_true, y_gbert)

{'precision': 0.956, 'recall': 0.9571, 'f1_macro': 0.9766, 'accuracy': 0.9939}

# Evaluate Fine-tuned christinbeck/GHisBERT

In [ ]:
#ghisbert_path = "../models/ghisbert-mwb-NER" # uncomment to regenerate annotations
#ghisbert = pipeline("token-classification", model=ghisbert_path)
#finetuned_ghisbert_test_df = test_df[["tokens"]].copy()
#finetuned_ghisbert_test_df["labels"] = finetuned_ghisbert_test_df["tokens"].apply(lambda x: get_aligned_labels(x, ghisbert(" ".join(x), aggregation_strategy="first")))
#finetuned_ghisbert_test_df.to_csv("../data/predictions/mwb-texts_NER_test_ghisbert.tsv", sep="\t", index=False)

finetuned_ghisbert_test_df = pd.read_csv("../data/predictions/mwb-texts_NER_test_ghisbert.tsv", sep="\t", converters={0: ast.literal_eval, 1: ast.literal_eval})
finetuned_ghisbert_test_df

,tokens,labels
0,"[sîn, ungevüegez, rîs, in, der, hende, als, ei...","[O, O, O, O, O, O, O, O, O, O, O, O, B, O, O, ..."
1,"[hiez, daz, aller, valsch, an, im, verswant,, ...","[O, O, O, O, O, O, O, O, O, O, B, O, O, O, O, ..."
2,"[het, aldâ, genomn, der, stolze, küene, Wâleis...","[O, O, O, O, O, O, B, B, O, B, O, B, B, B, O, ..."
3,"[erslagn., nu, vergebt, im, sîne, schulde, dur...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
4,"[umbe, begunder, gâhen,, des, küneges, vanen, ...","[O, O, O, O, O, O, O, O, O, O, B, O, O, O, O, ..."
...,...,...
595,"[guoten, ritter, zimet,, swenn, er, den, schil...","[O, O, O, O, O, O, O, O, O, B, O, O, O, O, O, ..."
596,"[der, brust, bewart,, so, ist, werder, prîs, d...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
597,"[ein, herre, genant, alsus,, der, künec, Iels,...","[O, O, O, O, O, O, B, O, B, O, B, O, O, O, B, ..."
598,"[vor, im, her, gesant,, sît, ichz, lebende, im...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
599,"[lêret, ir, mûze, alsus, volrecken,, nâch, den...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."

In [11]:
y_ghisbert = list(finetuned_ghisbert_test_df["labels"].explode()) #list(chain(*y_ghisbert)) # flatten list

evaluate(y_true, y_ghisbert)

{'precision': 0.8068, 'recall': 0.8633, 'f1_macro': 0.9105, 'accuracy': 0.9759}

# Evaluate TreeTagger

In [12]:
def get_tt_label(tagger, tokens):
    output = tagger.tag_text([f"<w>{x}</w>" for x in tokens])
    labels = []
    
    is_content = False
    was_punct = False
    for i in range(len(output)):
        if output[i] == "<w>":
            is_content = True
            continue
        if not is_content:
            continue
            
        if output[i] == "</w>" and was_punct:
            labels.append("O")
            was_punct = False
            continue
        
        pos = output[i].split("\t")[1] # MEMO: output is a list with {token}\t{POS}\t{lemma}
        if pos == "PUNCT":
            was_punct = True
            continue
        if pos == "PROPN":
            labels.append("B")
        else:
            labels.append("O")
        is_content = False
    return labels

In [ ]:
#tagger = treetaggerwrapper.TreeTagger(TAGDIR='../lib/tree-tagger/tree-tagger-linux-3.2.4', TAGPARFILE='../lib/tree-tagger/middle-high-german.par', TAGOPT="-token -lemma -sgml") # uncomment to regenerate annotations
#tt_test_df = test_df[["tokens"]].copy()
#tt_test_df["labels"] = tt_test_df["tokens"].apply(lambda x: get_tt_label(tagger, x))
#tt_test_df.to_csv("../data/predictions/mwb-texts_NER_test_tt.tsv", sep="\t", index=False)

tt_test_df = pd.read_csv("../data/predictions/mwb-texts_NER_test_tt.tsv", sep="\t", converters={0: ast.literal_eval, 1: ast.literal_eval})
tt_test_df

,tokens,labels
0,"[sîn, ungevüegez, rîs, in, der, hende, als, ei...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
1,"[hiez, daz, aller, valsch, an, im, verswant,, ...","[O, O, O, O, O, O, O, O, O, O, B, O, O, O, O, ..."
2,"[het, aldâ, genomn, der, stolze, küene, Wâleis...","[O, O, O, O, O, O, B, B, O, B, O, B, O, B, O, ..."
3,"[erslagn., nu, vergebt, im, sîne, schulde, dur...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
4,"[umbe, begunder, gâhen,, des, küneges, vanen, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
...,...,...
595,"[guoten, ritter, zimet,, swenn, er, den, schil...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
596,"[der, brust, bewart,, so, ist, werder, prîs, d...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
597,"[ein, herre, genant, alsus,, der, künec, Iels,...","[O, O, O, O, O, O, B, O, B, O, O, O, O, B, B, ..."
598,"[vor, im, her, gesant,, sît, ichz, lebende, im...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
599,"[lêret, ir, mûze, alsus, volrecken,, nâch, den...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."

In [14]:
y_tt = list(tt_test_df["labels"].explode())

evaluate(y_true, y_tt)

{'precision': 0.9622, 'recall': 0.7774, 'f1_macro': 0.9253, 'accuracy': 0.9822}

# Evaluate off-the-shelf NER model

In [15]:
def get_stanza_entities(stanza_output):
    entities = []
    for entity in stanza_output.ents:
        if entity.type in ["PER", "LOC"]:
            entities.append({"word": entity.text, "start": entity.start_char, "end": entity.end_char})
    return entities

In [ ]:
#stanza = stanza.Pipeline(lang='de', processors='tokenize,ner') # uncomment to regenerate annotations
#stanza_test_df = test_df[["tokens"]].copy()
#stanza_test_df["labels"] = stanza_test_df["tokens"].apply(lambda x: get_aligned_labels(x, get_stanza_entities(stanza(" ".join(x)))))
#stanza_test_df.to_csv("../data/predictions/mwb-texts_NER_test_stanza.tsv", sep="\t", index=False)

stanza_test_df = pd.read_csv("../data/predictions/mwb-texts_NER_test_stanza.tsv", sep="\t", converters={0: ast.literal_eval, 1: ast.literal_eval})
stanza_test_df

,tokens,labels
0,"[sîn, ungevüegez, rîs, in, der, hende, als, ei...","[O, O, O, O, O, O, O, O, O, O, B, O, B, O, B, ..."
1,"[hiez, daz, aller, valsch, an, im, verswant,, ...","[O, O, O, O, O, O, O, O, O, O, B, O, O, O, O, ..."
2,"[het, aldâ, genomn, der, stolze, küene, Wâleis...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
3,"[erslagn., nu, vergebt, im, sîne, schulde, dur...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
4,"[umbe, begunder, gâhen,, des, küneges, vanen, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
...,...,...
595,"[guoten, ritter, zimet,, swenn, er, den, schil...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
596,"[der, brust, bewart,, so, ist, werder, prîs, d...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
597,"[ein, herre, genant, alsus,, der, künec, Iels,...","[O, O, O, O, O, O, O, O, B, O, O, O, O, O, B, ..."
598,"[vor, im, her, gesant,, sît, ichz, lebende, im...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
599,"[lêret, ir, mûze, alsus, volrecken,, nâch, den...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."

In [17]:
y_stanza = list(stanza_test_df["labels"].explode())

evaluate(y_true, y_stanza)

{'precision': 0.868, 'recall': 0.1932, 'f1_macro': 0.6427, 'accuracy': 0.9413}

# Evaluate String Matching

In [18]:
import re

def remove_punctuation(token):
    punct_pattern = r"\[\]_/()?!.,:;><›‹»«“”„‘’‚‟‛'" + '"'
    return re.sub(f"^[{punct_pattern}]*?(.+?)[{punct_pattern}]*$", "\\1", token)

names = list(pd.read_csv("../models/names-mwb.tsv", sep="\t", header=0, names=["name"])["name"])
len(names)

4974

In [19]:
type_list_test_df = test_df[["tokens"]].copy()
type_list_test_df["labels"] = type_list_test_df["tokens"].apply(lambda x: ["B" if remove_punctuation(token) in names else "O" for token in x])
type_list_test_df

,tokens,labels
0,"[sîn, ungevüegez, rîs, in, der, hende, als, ei...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
1,"[hiez, daz, aller, valsch, an, im, verswant,, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
2,"[het, aldâ, genomn, der, stolze, küene, Wâleis...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
3,"[erslagn., nu, vergebt, im, sîne, schulde, dur...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
4,"[umbe, begunder, gâhen,, des, küneges, vanen, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
...,...,...
595,"[guoten, ritter, zimet,, swenn, er, den, schil...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
596,"[der, brust, bewart,, so, ist, werder, prîs, d...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
597,"[ein, herre, genant, alsus,, der, künec, Iels,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, B, O, ..."
598,"[vor, im, her, gesant,, sît, ichz, lebende, im...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
599,"[lêret, ir, mûze, alsus, volrecken,, nâch, den...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."

In [20]:
y_type_list = list(type_list_test_df["labels"].explode())

evaluate(y_true, y_type_list)

{'precision': 0.9957, 'recall': 0.5198, 'f1_macro': 0.8325, 'accuracy': 0.9661}